### ISSUE TITLE
Proper use is not clear

### ISSUE THREAD

**Issue by Reonarudo** [soffes/SyntaxKit#12]
The lack of a wiki makes the use of this potential great framework hard to use.

For example I can't figure out how to set the view background colour to the one defined in the theme and the provided example was not enough to clarify.

**Comment by soffes** [comment]
Documentation on how to make TextMate themes is outside the scope of this repo's documentation. [This](http://tmtheme-editor.herokuapp.com/#!/editor/theme/Monokai) seems like a good resource.
