### ISSUE TITLE
Can't import on swift 4 ios 9

### ISSUE THREAD

**Issue by mrtungdev** [soffes/SyntaxKit#22]
I using it with pod.
But when I
`import SyntaxKit`
I got error:
`No such module 'SyntaxKit'`

**Comment by alehed** [comment]
Is SyntaxKit building? Do you mean Xcode 9?

Make sure SyntaxKit is included `General > Linked Frameworks and Libraries` and `Build Phases > Target Dependencies`.

I don't use CocoaPods myself, so I might not be much help here. For me it builds locally with the latest version of Xcode.

**Comment by mrtungdev** [comment]
Thank you.
this lib currently not working with CocoaPods.
