### ISSUE TITLE
Cannot invoke initializer for type 'Language'?

### ISSUE THREAD

**Issue by mrtungdev** [soffes/SyntaxKit#23]
Hello!
I follow your readme but I got this:

`Cannot invoke initializer for type 'Language' with an argument list of type '(dictionary: [NSObject : AnyObject])'`

![screen shot 2017-09-23 at 8 38 09](https://user-images.githubusercontent.com/13881055/30773680-7c09f772-a09f-11e7-8a2a-7793ff5e493c.png)

**Comment by alehed** [comment]
Language does not have any public initializers.

See the readme from alehed/SyntaxKit for examples.

**Comment by alehed** [comment]
Wait… are you using the main project (soffes/SyntaxKit)? It is still written in Swift 2. I guess after conversion it takes `[String: Any]` or something similar. You can find the exact type in your header file.
